#pragma config(Sensor, dgtl3,  IR_sensor,      sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

 while(true){
   writeDebugStreamLine("intl %d", SensorValue(IR_sensor));
}
}
