#pragma config(Sensor, in1,    IR_1,           sensorReflection)
#pragma config(Sensor, in2,    IR_2,           sensorReflection)
#pragma config(Sensor, in3,    IR_3,           sensorReflection)
#pragma config(Sensor, in4,    IR_4,           sensorReflection)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

 while(true){
   //Light reflected -- below 400
   writeDebugStreamLine("intl %d", SensorValue(IR_1));
   writeDebugStreamLine("intl %d", SensorValue(IR_2));
   writeDebugStreamLine("intl %d", SensorValue(IR_3));
   writeDebugStreamLine("intl %d", SensorValue(IR_4));
}
}
