#pragma config(Motor,  port2,           leftmotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (true){
	motor[leftmotor] = 127;
	delay(5000);
	motor[leftmotor] = 0;
	break;
	}

}
