#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Motor,  port2,           right_motor,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Added for servo motor
task main() {
    while (1){

		motor[right_motor] = 50;
		untilEncoderCounts(480, quad);
		motor[right_motor] = 0;

	}

}
