#pragma config(Sensor, in1,    IR_1,           				sensorReflection)
#pragma config(Sensor, in2,    IR_2,           				sensorReflection)
#pragma config(Sensor, in3,    IR_3,           				sensorReflection)
#pragma config(Sensor, in4,    IR_4,           				sensorReflection)
#pragma config(Sensor, in5,    sharp_1,        				sensorAnalog)
#pragma config(Sensor, in6,    sharp_2,        				sensorAnalog)
#pragma config(Sensor, in7,    sharp_3,        				sensorAnalog)
#pragma config(Sensor, in8,    sharp_4,        				sensorAnalog)
#pragma config(Sensor, dgtl1,  on_off_switch,  				sensorDigitalIn)
#pragma config(Sensor, dgtl2,  collector_switch, 			sensorDigitalIn)
#pragma config(Sensor, dgtl3,  release_switch_left, 	sensorDigitalIn)
#pragma config(Sensor, dgtl4,  release_switch_right, 	sensorDigitalIn)
#pragma config(Sensor, dgtl6,  shaft_encoder,  				sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  compass_LSB,    				sensorDigitalIn)
#pragma config(Sensor, dgtl10, compass_Bit3,   				sensorDigitalIn)
#pragma config(Sensor, dgtl11, compass_Bit2,   				sensorDigitalIn)
#pragma config(Sensor, dgtl12, compass_MSB,    				sensorDigitalIn)
#pragma config(Motor,  port2,  left_motor,    				tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,  right_motor,   				tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,  collector_motor, 			tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"


task main(){
	init();
	startTask(check_main_switch);
	startTask(set_distance);
	startTask(check_line);
	startTask(start_mission);
	startTask(check_current_orientation);
	startTask(ball_detection);
	startTask(opponent_detection);


	while(1){
		if(!main_switch.run_motor){
			stop_motor();
		}
	}

}
