#pragma config(Sensor, in1,    sharp_front_bottom, sensorAnalog)
#pragma config(Sensor, dgtl2,  on_off_switch,  sensorDigitalIn)
#pragma config(Sensor, dgtl3,  line_sensor_front_left, sensorDigitalIn)
#pragma config(Sensor, dgtl8,  line_sensor_front_right, sensorDigitalIn)
#pragma config(Motor,  port2,           right_motor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           left_motor,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "state_machine.h"


task main()
{
	init();

	bottom_distance = distance_front_bottom();

	while(1){
		startTask(main_task);
		check_line();
	}

}
